version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservices_db
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

#172.17.0.1 - internal docker host

  producto-service:
    build:
      context: ./producto-service
      dockerfile: Dockerfile
    container_name: producto-service
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8080/api/v1/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.17.0.1:3309/microservices_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - INVENTORY_SERVICE_URL=http://inventario-service:9090
      - SPRING_SECURITY_API_KEY=3f7a0e2c-8c5a-4e31-b8c6-04fd6e5f97a9
    depends_on:
      - mysql
    networks:
      - my-network

  inventario-service:
    build:
      context: ./inventario-service
      dockerfile: Dockerfile
    container_name: inventario-service
    ports:
      - "9090:9090"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:9090/api/v1/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.17.0.1:3309/microservices_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - PRODUCT_SERVICE_URL=http://producto-service:8080
      - SPRING_SECURITY_API_KEY=3f7a0e2c-8c5a-4e31-b8c6-04fd6e5f97a9
      - LINKTIC_MICROSERVICES_PRODUCTS_URL=http://172.17.0.1:8080/api/v1
      - LINKTIC_MICROSERVICES_PRODUCTS_GET_PRODUCT_BY_ID_ENDPOINT=/products
      - LINKTIC_MICROSERVICES_PRODUCTS_CREATE_PRODUCT_ENDPOINT=/products
    depends_on:
      - mysql
      - producto-service
    networks:
      - my-network

volumes:
  mysql-data:

networks:
   my-network:
     driver: bridge
